[build-system]
requires = ["hatchling", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[project]
name = "aye_arr"
version = "1.0.0"
dynamic = ["readme"]
authors = [
    { name = "Chris P", email = "chris@pimoroni.com" },
]
maintainers = [
    { name = "Chris P", email = "chris@pimoroni.com" },
]
description = "Aye Arr: Infrared TX/RX library for RP2040/2350 MicroPython"
classifiers = [
    "License :: OSI Approved :: MIT License"
]

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [
  { path = "README.md" },
  { text = "\n" },
  { path = "CHANGELOG.md" }
]

[tool.hatch.build]
include = [
    "aye_arr/*.py",
    "aye_arr/nec/*.py",
    "aye_arr/nec/*.md",
    "aye_arr/nec/remotes/*.py",
    "aye_arr/nec/remotes/*.md",
    "aye_arr/pulse/*.py",
    "aye_arr/pulse/pio/*.py",
    "aye_arr/pulse/*.md",
    "docs/*.md",
    "README.md",
    "CHANGELOG.md",
    "LICENSE.txt"
]

[tool.hatch.build.targets.wheel]
sources = ["src"]

[tool.ruff]
exclude = [
    '.tox',
    '.egg',
    '.git',
    '__pycache__',
    'build',
    'dist'
]
line-length = 200

[tool.codespell]
skip = """
./.tox,\
./.egg,\
./.git,\
./__pycache__,\
./build,\
./dist.\
"""

[tool.isort]
line_length = 200

[tool.check-manifest]
ignore = [
    'check.sh',
    'Makefile',
    'tox.ini',
    'tests/*',
    'examples/*',
    'examples/nec/*',
    'examples/nec/receive/*',
    'examples/nec/receive/remote/*',
    'examples/nec/send/*',
    'examples/boards/motor_shim/*',
    'examples/boards/plasma/*',
    'examples/boards/tiny_2350/*',
    'tools/*',
    'requirements-dev.txt',
    'package.json'
]

[project.urls]
GitHub = "https://www.github.com/pimoroni/aye_arr"
Homepage = "https://www.pimoroni.com"